redis:
    host: t1.svr.nilone.cn
    port: 6379
    password: qwe123
    db: 0
    maxIdle: 20
    maxActive: 100
    Timeout: 5
scan:
    nWorkers: 100
    ports: [80,81,88,118,808,1080,3128,8080,8081,8088,8888,9999]
    requests: requests.xml
craw:
    template: E:\test\template
    task: task.xml
    userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
    interval: 10
    distance: 5
checker:
    anony:
        checkUrl: http://ip.nilone.cn/chkproxy.json
        nWorkers: 20
        checkSize: 1024
        maxBodySize: 1048576
    history:
        nWorkers: 10
        checkUrls: http://ip.nilone.cn/chkproxy.json
        checkSize: 1024
        userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
    